version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VITE_BASE_URL: "http://backend:3000"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
